# Generated by Django 2.1.1 on 2018-10-31 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Textbook',
            fields=[
                ('post_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
