# Generated by Django 2.1.2 on 2018-11-12 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='textbook',
            name='date_added',
            field=models.DateField(default='1111-11-11', max_length=50),
        ),
        migrations.AddField(
            model_name='textbook',
            name='subject',
            field=models.CharField(default='hello', max_length=5),
        ),
    ]
