# Generated by Django 2.1.2 on 2018-11-13 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20181112_2108'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
