# Generated by Django 2.1.2 on 2018-11-14 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='textbook',
            name='class_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='textbook',
            name='date_sold',
            field=models.DateField(default='1111-11-11', max_length=50),
        ),
        migrations.AddField(
            model_name='textbook',
            name='donate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='textbook',
            name='edition',
            field=models.CharField(default='DEFAULT_EDITION', max_length=20),
        ),
        migrations.AddField(
            model_name='textbook',
            name='isbn',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='textbook',
            name='paid_type',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='textbook',
            name='present',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='textbook',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='textbook',
            name='sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='textbook',
            name='title',
            field=models.CharField(default='DEFAUL_TITLE', max_length=100),
        ),
        migrations.AlterField(
            model_name='textbook',
            name='subject',
            field=models.CharField(default='DEFAULT_SUBJECT', max_length=5),
        ),
    ]
